Repository AnnabellFlem/AlarmClock, pull requests merged in 2018-10, with the labels that each got.

#2 Add LICENSE
  LICENSE
Labels: good first issue

#1 Create basic WPF project
  AlarmClock.csproj
  AlarmClock.sln
  App.config
  App.xaml
  App.xaml.cs
  MainWindow.xaml
  MainWindow.xaml.cs
  Properties/AssemblyInfo.cs
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  Properties/Settings.Designer.cs
  Properties/Settings.settings
Labels: enhancement

#3 Implemented basic Log In MVVM (no connection)
  AlarmClock.csproj
  AlarmClock.sln.DotSettings
  App.xaml.cs
  MainWindow.xaml.cs
  Properties/Annotations.cs
  src/Models/User.cs
  src/ViewModels/LogInViewModel.cs
  src/Views/AlarmClock.xaml
  src/Views/AlarmClock.xaml.cs
  src/Views/LogInView.xaml
  src/Views/LogInView.xaml.cs
  src/Views/MainWindow.xaml
  src/Views/MainWindow.xaml.cs
Labels: enhancement

#4 Changed LogInView to be a UserControl
  AlarmClock.csproj
  src/App.xaml
  src/App.xaml.cs
  src/ViewModels/LogInViewModel.cs
  src/Views/AlarmClock.xaml.cs
  src/Views/LogInView.xaml
  src/Views/LogInView.xaml.cs
  src/Views/MainWindow.xaml
Labels: enhancement

#5 Added RelayCommand class
  src/RelayCommand.cs
  src/Views/LogInView.xaml
Labels: bug, enhancement

#6 Implemented basic navigation
  AlarmClock.csproj
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  src/App.xaml
  src/App.xaml.cs
  src/MainWindow.xaml
  src/MainWindow.xaml.cs
  src/Managers/NavigationManager.cs
  src/Misc/NavigationModel.cs
  src/Misc/RelayCommand.cs
  src/Models/User.cs
  src/ViewModels/SignInViewModel.cs
  src/Views/MainView.xaml
  src/Views/MainView.xaml.cs
  src/Views/MainWindow.xaml.cs
  src/Views/SignInView.xaml
  src/Views/SignInView.xaml.cs
  src/Views/SignUpView.xaml
  src/Views/SignUpView.xaml.cs
Labels: enhancement

#7 Clock model and repositories
  AlarmClock.csproj
  src/Models/Clock.cs
  src/Models/User.cs
  src/Repositories/ClockRepository.cs
  src/Repositories/IClockRepository.cs
  src/Repositories/IUserRepository.cs
  src/Repositories/UserRepository.cs
Labels: enhancement

#9 Basic Main model window
  .gitignore
  AlarmClock.csproj
  App.config
  resources/alarmclock.ico
  resources/btns/add.png
  resources/btns/bell.png
  resources/btns/delete.png
  resources/btns/logout.png
  resources/btns/man-user.png
  resources/btns/sign-in32.png
  src/MainWindow.xaml
  src/Misc/RelayCommand.cs
  src/ViewModels/MainViewModel.cs
  src/Views/MainView.xaml
  src/Views/MainView.xaml.cs
Labels: enhancement

#10 Changed Ecrypter to use object instead of tuple
  src/Misc/Encrypter.cs
  src/Models/User.cs
Labels: bug

#11 Implemented Sign up
  .gitignore
  AlarmClock.csproj
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  src/Misc/NotifyPropertyChanged.cs
  src/Misc/RelayCommand.cs
  src/Models/Clock.cs
  src/Models/User.cs
  src/Repositories/IUserRepository.cs
  src/Repositories/UserRepository.cs
  src/ViewModels/MainViewModel.cs
  src/ViewModels/SignInViewModel.cs
  src/ViewModels/SignUpViewModel.cs
  src/Views/SignInView.xaml
  src/Views/SignUpView.xaml
  src/Views/SignUpView.xaml.cs
Labels: enhancement, good first issue

#12 Implemented Sign Out from the Main page
  AlarmClock.csproj
  resources/btns/signout.png
  src/ViewModels/MainViewModel.cs
  src/Views/MainView.xaml
Labels: enhancement, good first issue

#13 Added AddAlarmClock command
  AlarmClock.csproj
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  resources/btns/sign-in32.png
  src/ViewModels/MainViewModel.cs
  src/ViewModels/SignInViewModel.cs
  src/Views/MainView.xaml
Labels: enhancement

#14 Functional testing
  AlarmClock.csproj
  App.config
  packages.config
  src/Models/User.cs
  src/Views/MainView.xaml
  src/Views/SignInView.xaml
  src/Views/SignUpView.xaml
  tests/SignInTest.cs
  tests/SignUpTest.cs
Labels: enhancement, good first issue

#16 Fixed add with user and basic ring
  AlarmClock.csproj
  resources/btns/save.png
  resources/btns/undo.png
  src/Models/AlarmItem.cs
  src/Models/Clock.cs
  src/Repositories/ClockRepository.cs
  src/ViewModels/MainViewModel.cs
  src/Views/MainView.xaml
Labels: enhancement, help wanted

#17 Update README
  README.md
Labels: enhancement, good first issue

#19 Added bug info to the README
  README.md
Labels: enhancement, good first issue
