Repository AnnabellFlem/AlarmClock, pull requests merged in 2018-11, with the labels that each got.

#22 Update README
  README.md
Labels: good first issue

#21 Logging, Clock updating, refactoring
  AlarmClock.csproj
  Properties/Resources.Designer.cs
  Properties/Resources.resx
  src/App.xaml
  src/App.xaml.cs
  src/Misc/FileFolderHelper.cs
  src/Misc/Logger.cs
  src/Models/AlarmItem.cs
  src/Models/Clock.cs
  src/ViewModels/MainViewModel.cs
  src/ViewModels/SignInViewModel.cs
  src/ViewModels/SignUpViewModel.cs
Labels: enhancement, good first issue

#23 Serialization, refactoring and other
  AlarmClock.csproj
  src/App.xaml.cs
  src/Managers/SerializationManager.cs
  src/Managers/StationManager.cs
  src/Misc/FileFolderHelper.cs
  src/Misc/Logger.cs
  src/Misc/NavigationModel.cs
  src/Misc/SerializationHelper.cs
  src/Models/AlarmItem.cs
  src/Models/Clock.cs
  src/Models/User.cs
  src/Repositories/ClockRepository.cs
  src/Repositories/IClockRepository.cs
  src/Repositories/IUserRepository.cs
  src/Repositories/UserRepository.cs
  src/ViewModels/MainViewModel.cs
  src/ViewModels/SignInViewModel.cs
  src/ViewModels/SignUpViewModel.cs
  src/Views/MainView.xaml
  src/Views/SignInView.xaml.cs
  src/Views/SignUpView.xaml.cs
Labels: enhancement

#25 Loader base and tests fix
  AlarmClock.csproj
  packages.config
  src/MainWindow.xaml
  src/MainWindow.xaml.cs
  src/Managers/LoaderManager.cs
  src/Managers/NavigationManager.cs
  src/Managers/SerializationManager.cs
  src/Misc/ILoaderOwner.cs
  src/Misc/NavigationModel.cs
  src/ViewModels/MainWindowViewModel.cs
  src/ViewModels/SignInViewModel.cs
  src/Views/SignInView.xaml.cs
  tests/SignInTest.cs
  tests/SignUpTest.cs
Labels: bug, enhancement, good first issue

#29 Added known bugs to the README
  README.md
Labels: bug, good first issue

#33 Dispatcher time
  src/ViewModels/MainViewModel.cs
Labels: bug

#34 Refactoring and improvements
  AlarmClock.csproj
  packages.config
  src/Misc/CountConverter.cs
  src/Models/AlarmItem.cs
  src/ViewModels/MainViewModel.cs
  src/Views/MainView.xaml
  src/Views/MainView.xaml.cs
Labels: enhancement, good first issue
